### ISSUE TITLE
the client can not access ipv6 although it can get the ipv6 address

### ISSUE THREAD

**Issue by YunEr-Wang** [openwrt/odhcpd#106]
Hello, everyone, my laptop can get the IPV6 address, but it can not connect to the IPv6 network.  I use esxi loaded LEDE (it should be the latest).It's strange that sometimes it can be connected, but once the router is restarted, it won't work. I really hope that you can help me . Thanks.

My LEDE network config
```
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'

config interface 'lan'
	option type 'bridge'
	option ifname 'eth0 eth1 eth2'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option ip6assign '60'

config interface 'wan'
	option ifname 'eth3'
	option _orig_ifname 'eth3'
	option _orig_bridge 'false'
	option proto 'pppoe'
	option username 'XXXXXXX'
	option password 'XXXXXXX'
	option ipv6 'auto'

````
dhcp config
```
config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option filterwin2k '0'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option nonegcache '0'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.auto'
	option nonwildcard '1'
	option localservice '1'

config dhcp 'wan'
        option interface 'wan'
        option ignore '1'
        option ra 'relay'
        option dhcpv6 'relay'
        option ndp 'relay'
        option master '1'

config dhcp 'wan6'                               
        option dhcpv6 'disabled'           
        option ra 'relay'                        
        option ndp 'relay'     
        option master '1'  

config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option limit '150'
        option leasetime '12h'
        option ra 'relay'
        option dhcpv6 'relay'
        option ndp 'relay'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

```
ipv6 neigh proxy info
```
2001:250:7801:c263:ec53:72e9:ae54:c11c dev br-lan  proxy
2001:250:7801:bd98:d829:fdae:90b0:9f3f dev pppoe-wan  proxy
```

**Comment by troniac** [comment]
Hello Dude,

I experiencing same issue. I setup IPv6 Tunne because my ISP is stupid and has IPv6 Prefix Delegation Disabled on the Router. So I get only IPv6 Hosts not Networks from it. So I setup my own OpenWRT Router with 6in4 Tunnel and every device gets an IPv6 Address from the OpenWRT Router from the Hurricane IPv6 Tunnelbroker.

But when I try to ping I can only ping the Router and my Devices but I can not access the Internet via IPv6 even if I disable the Firewall with ip6tables -F. When I traceroute6 ipv6.google.com I see that my Client tries to reach the google Address via the OpenWRT Router IPv6 Address and the Router is sending the ICMP Packages to the destination I can see it with tcpdump and they are acknowledged and send back to the router but not to the client which initiated the traceroute... so the client sees Timeout :(

I disabled the ipv6 firewall on client as well this is not causing the problem :(
