### ISSUE TITLE
Feature Request: Feed leases via ubus

### ISSUE THREAD

**Issue by aparcar** [openwrt/odhcpd#113]
To share leases between multiple odhcpd instances (running on multiple hosts) a way is required to add leases to odhcpd without actually connecting a device. Instead of using lease files it would be handy to have a ubus call.

@dangowrt can you look into this?

**Comment by aparcar** [comment]
ping @dangowrt

**Comment by altergui** [comment]
reping @dangowrt

**Comment by altergui** [comment]
i'm (re)evaluating the possibility of using odhcpd as dhcpv6 server in libremesh (instead of dnsmasq-dhcpv6) to converge with upstream and benefit from all the progress done into supporting native ipv6 uplinks.
this is feature request is still a blocker.
@spiccinini has read the relevant code and concluded he'd need a significant amount of time to solve this.
what about you?

**Comment by altergui** [comment]
this issue on libremesh is still open https://github.com/libremesh/lime-packages/issues/294

**Comment by spiccinini** [comment]
This issue can be closed now as it is now in master https://git.openwrt.org/?p=project/odhcpd.git;a=commit;h=8f27697b9b82420890cedd429622052c8b67cea1
