### ISSUE TITLE
odhcpd fails to CONFIRM a prior DHCPv6 lease

### ISSUE THREAD

**Issue by rsmarples** [openwrt/odhcpd#12]
It sends back a status code of 04 for the IAID which causes dhcpcd to SOLICIT for a new address. odhcpd then sends the address we were trying to confirm back to dhcpcd.

Tested using the latest dhcpcd code from fossil, found here:
http://roy.marples.name/projects/dhcpcd/timeline

**Comment by sbyx** [comment]
Yes, that was more or less intentional. I can't remember 100% as to why I did it this way. But I think it had something to do with some clients not reacting well to address changes in the confirm (if they happened) so I just always let them redo the assignment. If I have some time I can investigate this again.

**Comment by rsmarples** [comment]
You're not supposed to change the addresses in the confirm. In-fact confirm is meant to very lightweight on the server side. ISC dhcpd, WIDE dhcp6s and dnsmasq for example don't send back any addresses or options on their reply to a confirm, just a status code. The client has to use the last lease from the other messages.
