### ISSUE TITLE
odhcpd stops handing out upstream prefix after 2 or 3 days

### ISSUE THREAD

**Issue by ktgeek** [openwrt/odhcpd#65]
I get my v6 prefix via dhcp from my upstream provider (comcast.)  I've noticed that after 2 or 3 days, odhcpd stops handing out the upstream prefix and doing router advertisements for it, resulting in the other network clients being unable to route to the internet.  Restarting odhcpd remedies the problem.

I'm not sure the cause, I'm not even sure how to start tracking down the cause.  I'd love to provide more info if there any suggestions for things to look at?

This behaviors has happened since I upgraded OpenWRT to 15.05, but I'm hand maintaining odhcpd.  I'm currently running off commit aa3a13659ad6d2934f31e47a805b462269645f2d

**Comment by ktgeek** [comment]
Just a quick update.  I had ra_default set to 1 when I sent my original report, but in trying to simplify my setup, I set it back to the default of 0 to see if there was any behavior change.  This morning I lost my ipv6 route to the internet and found this in the logs:

`odhcpd[29226]: A default route is present but there is no public prefix on br-lan thus we don't announce a default route!`

I looked at br-lan and saw it still had an address on the public prefix given to me by Comcast.  Again, restarting odhcpd fixed the issue and the public prefix is being broadcast and proper addresses are handed out.

I don't understand enough of the code yet to debug it but the fact the correct behaviour happens on restart says to me there is a bug somewhere related to refreshing the default route.  I need to understand more of what's going on, but I think the logic starting at router.c:257 might be wrong or the condition at router.c:322 is wrong.

Anything I can do to help narrow it done I'd be more than happy to do.

**Comment by willmo** [comment]
I've observed the same thing, although the frequency is somewhat irregular. I also have Comcast, and I'm running OpenWrt trunk r46900.

I've determined that the receive buffer of odhcpd's `rtnl_event` socket is filling up, which causes the kernel to set the error condition on the socket, with error `ENOBUFS`. This is detected by the uloop event loop [here](http://git.openwrt.org/?p=project/libubox.git;a=blob;f=uloop.c;h=ea160a06a0f3d9127e021130fb4227e04ce3d1b5;hb=HEAD#l272), and as you can see it stops polling for events on that socket altogether, since `ULOOP_ERROR_CB` is not set for this socket. This means odhcpd no longer [checks for address updates](https://github.com/sbyx/odhcpd/blob/master/src/ndp.c#L468) on any interfaces, and therefore is no longer aware of extensions of prefixes' valid lifetimes at lease renewals, and eventually decides they've expired. There is no recovery aside from restarting odhcpd, which obviously fixes it because it gets all of the address info again from scratch.

In this state, if you cat /proc/net/netlink, you should be able to see this socket having a full receive buffer and an ever-increasing number of drops:

```
# cat /proc/net/netlink 
sk       Eth Pid    Groups   Rmem     Wmem     Dump     Locks     Drops     Inode
82f90c00 0   21715  00000001 0        0        0 2        0        2211146 
8384cc00 0   0      00000000 0        0        0 2        0        3       
82f6e000 0   13579  00000001 0        0        0 2        0        562200  
82c63800 0   13222  00000000 0        0        0 2        0        561799  
82f6f000 0   13580  00000001 0        0        0 2        0        562205  
82822800 0   14432  00000000 0        0        0 2        0        2195870 
82c63000 0   4207526 00000001 0        0        0 2        14       561800  
82823c00 0   4294963187 00000504 164160   0        0 2        32449    2195874 
82ecc800 0   13817  00000440 0        0        0 2        27246    562715  
83924c00 10  0      00000000 0        0        0 2        0        10      
83b4e400 15  1      ffffffff 0        0        0 2        0        179     
8384d800 15  0      00000000 0        0        0 2        0        5       
82c62400 15  8401830 00000001 0        0        0 2        0        561801  
8328e000 16  8402188 00000000 0        0        0 2        0        562213  
8328e400 16  12596492 00000000 0        0        0 2        145      562214  
82f6f800 16  13579  00000000 0        0        0 2        0        562201  
82f6e800 16  4207884 0000003c 0        0        0 2        0        562207  
82f6fc00 16  13580  00000000 0        0        0 2        0        562206  
82f6f400 16  4207883 0000003c 0        0        0 2        0        562202  
830f7800 16  12596491 00000000 0        0        0 2        0        562211  
838e1000 16  0      00000000 0        0        0 2        0        8       
830f7400 16  8402187 00000000 0        0        0 2        0        562210
```

It's the one with `00000504` in the Groups column.

[If you google](https://www.google.com/search?q=netlink+enobufs), `ENOBUFS` seems to be an occasional fact of life on netlink sockets, and other daemons appear to be equipped to handle it. For example, dnsmasq [absorbs it and keeps going](http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=blob;f=src/netlink.c;h=753784dc20b44f83529b3c0eae472c280433fc71;hb=HEAD#l182), while OpenWrt's own netifd [increases the receive buffer size and then gets a full dump in case it missed anything](http://git.openwrt.org/?p=project/netifd.git;a=blob;f=system-linux.c;h=f51c0785911e486ca40bdd886e9e2b82cb846fcb;hb=HEAD#l104). One can also set the `NETLINK_RECV_NO_ENOBUFS` option to have the kernel ignore drops/congestion altogether. You can see in my /proc/net/netlink output above that dnsmasq's netlink socket (inode 562715) has had a number of drops, but it continues working because dnsmasq absorbs the error rather than giving up. 

I'd like to help fix this for odhcpd, but I'm not sure what the appropriate strategy is, and I'd like to know what @sbyx thinks. It's important to note that one must not only clear the socket's error condition, which can be done with `getsockopt(fd, SOL_SOCKET, SO_ERROR, ...)`, but also [clear netlink's `NETLINK_CONGESTED` bit](https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/net/netlink/af_netlink.c?h=linux-4.1.y#n295), which requires a `recvmsg()` or similar.

As a side note, the socket's receive buffer might be less likely to fill up with the latest fixes to netifd, specifically [this one](http://git.openwrt.org/?p=project/netifd.git;a=commitdiff;h=014698606902e495c7b169bf30688a685cd72d64) and perhaps [this one](http://git.openwrt.org/?p=project/netifd.git;a=commitdiff;h=ebd3d8417c7a08c03de2d38e8f43422428dd4094) (?). But this still seems like a defect worth fixing in odhcpd.

**Comment by sbyx** [comment]
I hope this will do the trick: https://github.com/sbyx/odhcpd/commit/e60710d1fe0c5bf19b9acf9b116e0645e8e114d1

Haven't been able to test it yet though.

**Comment by ktgeek** [comment]
@willmo Good catch!  I didn't even know where to start to look.  I am not in the failed state yet, but I can see the drops racking up on that socket.

@sbyx I'm going to wait until I'm in a fully failed state to confirm @willmo's findings, then I'll put your new code in place and give it a go.

---

Follow up:  I fully failed today, and as @willmo noted, the drops are racking up at about 2/sec.  I'll get the most recent version on my router in the next day and hopefully have good news soon.  Thanks, @sbyx!

**Comment by willmo** [comment]
As I mentioned before, I think you'll also have to call recvmsg() (until the receive buffer is empty?) in order to clear the NETLINK_CONGESTED flag. Otherwise the kernel won't deliver anything to the socket and will just set the error flag again. (At least on kernel 4.1.)

**Comment by sbyx** [comment]
Sorry, I don't have much time at hand to get into detailed testing at the moment.
Anyway I removed the "return" which should cause a fall-through to the regular recvmsg loop in case of errors.

**Comment by sbyx** [comment]
https://github.com/sbyx/odhcpd/commit/01d3f9d64486ac1daa144848944e877e7f0cb762

**Comment by willmo** [comment]
Thanks, I think that'll work nicely! I've put it on my router and I'll report back.

**Comment by ktgeek** [comment]
I put it on my router this morning as well.  Now we wait.

**Comment by ktgeek** [comment]
I had to reboot my router yesterday, so I haven't gone three or four days yet, but looking at the rem in /proc/net/netlink it's been at 0 and stayed at 0, so it looks like this is working.

Thanks, @sbyx!

**Comment by willmo** [comment]
Well, 0 drops could just be from the receive buffer size having been increased. I wanted to wait to confirm until I saw drops on the netlink socket, and verify that odhcpd was still working after that. I reduced the receive buffer size to 100 KB (below the default of 160 KB) to make drops happen sooner. :-)

Anyway, I've finally seen some drops on the socket and then waited until the next lease renewal to verify that odhcpd advertised the extended valid lifetime. Indeed it did. So I think we can declare a definitive victory. :-)
