### ISSUE TITLE
Link-local addresses for IPv6 DNS servers do not work for Linux systems

### ISSUE THREAD

**Issue by mamarley** [openwrt/odhcpd#76]
The commit https://github.com/sbyx/odhcpd/commit/5b12eeba475a3301c362cf59f138ec7aa60d2dd9 breaks IPv6 DNS with Linux systems.  If the system is configured to use IPv6 only, DNS lookups fail.  For dig, the error is "connection timed out; no servers could be reached".  I can reproduce this issue on Ubuntu 16.04 with NetworkManager.

**Comment by toreanderson** [comment]
Link-local DNS servers are perfectly valid, and has (in my experience) worked fine in NM [since 2011](https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=c3893b5325ca61261be1749490352f26b41bd479). Assuming Ubuntu isn't shipping an ancient NM, the behaviour you're seeing must have some other reason. What's the contents of your `/etc/resolv.conf` file? What's the result of `for NS in $(sed -n 's/^nameserver //p' /etc/resolv.conf); do dig @$NS . SOA; done`?

**Comment by mamarley** [comment]
The only nameserver listed is 127.0.1.1, which is because Network Manager uses dnsmasq as a local DNS server.   The output of the command is:

`
; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.1.1 . SOA
;; global options: +cmd
;; connection timed out; no servers could be reached
`

**Comment by toreanderson** [comment]
Ok, so this is a bug in [dnsmasq](http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2016q2/010454.html) and/or [NetworkManager](https://bugzilla.gnome.org/show_bug.cgi?id=764839). The links will take you to the upstream bug reports I just filed.

For now you should be able to work around the issue by disabling dnsmasq (try `sed -i /dns=dnsmasq/s/^/#/ /etc/NetworkManager/NetworkManager.conf`).

**Comment by toreanderson** [comment]
Fixed in NetworkManager git [master](https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=c328cf52f2b219feb5ae03fd40175f6b6ca73975) and [nm-1.2](https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=3ec40f9fa9c22aa17050299cbd0c5ca3f5edc825) branches. I believe this odhcpd issue could be closed.
